version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: testcafe
    versions:
    - 1.10.1
    - 1.11.0
    - 1.12.0
    - 1.13.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: graphql-tools
    versions:
    - 7.0.2
    - 7.0.3
  - dependency-name: tslib
    versions:
    - 2.1.0
  - dependency-name: wait-on
    versions:
    - 5.2.1
